#!/usr/bin/perl -w
# HoneySpy -- advanced honeypot environment
# Copyright (C) 2005  Robert Nowotniak
# Copyright (C) 2005  Michal Wysokinski
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

use strict;
use Switch;

my $komeda;
my $user = 0;
$| = 1;

print "+OK POP3 Ready localhost\n";

while(defined($komeda = <STDIN>)) {
	chop $komeda;

	switch($komeda){
		case /^USER /{
			print "+OK\n";
			$user = 1;
		}

		case /^PASS / {
			if($user == 1) {
				print "-ERR Invalid password or username\n";
			}
			else {
				print "-ERR give username first\n";
			}
		}
		case "QUIT" {
			print "+OK\n";
			exit 0;
		}
		else {
			if($user == 1) {
				print "-ERR use PASS password\n";
			}
			else {
				print "-ERR use USER name\n";
			}
		}
	}
}
