#!/usr/bin/env python

from twisted.protocols.telnet import *
from twisted.application import service,internet
from twisted.internet import protocol,defer,reactor,stdio
import sys,os

def loguj(arg):
    sys.stderr.write(arg)

######################################
# This class realize out fake telnet #
######################################
class TelnetProtocol(Telnet):
   
    def processChunk(self, chunk):
        """I take a chunk of data and delegate out to telnet_* methods
        by way of processLine. If the current mode is 'Done', I'll close
        the connection. """
        self.buffer = self.buffer + chunk

        #yech.
        for delim in self.delimiters:
            idx = self.buffer.find(delim)
            if idx != -1:
                break

        while idx != -1:
            buf, self.buffer = self.buffer[:idx], self.buffer[idx+2:]
            self.processLine(buf)
            if self.mode == 'Done':
                self.transport.loseConnection()
                os._exit(0) 

            for delim in self.delimiters:
                idx = self.buffer.find(delim)
                if idx != -1:
                    break
 
    def welcomeMessage(self):
        return "Wellcome to my protected computer\r\n"

    def connectionMade(self):
        Telnet.connectionMade(self)


    def telnet_User(self, user):
        loguj("Telnet tying to log with username: " + user + "\r\n")
        self.username = user
        self.write(IAC+WILL+ECHO+"password: ")
        return "Password"

    def checkUserAndPass(self,user,paswd):
        loguj("Telnet trying to log with username and passw: " + user +" "+paswd + "\r\n")
        return None

    def telnet_Command(self,cmd):
        self.write("cmd: " + cmd + "\r\n")
        return "Command"

    def dataReceived(self,data):
        Telnet.dataReceived(self,data)


class TelnetFactory(protocol.ServerFactory):
    protocol = TelnetProtocol
    def __init__(self, **kwargs): 
        self.users = kwargs

    def getUser(self, user):
        print "TelnetFactory.getUser"
        return defer.succeed(self.users.get(user, "No such user"))

#application=service.Application('serial')

factory = TelnetFactory()

setattr(factory, 'primes', '')
protocol = factory.buildProtocol('a');

stdio.StandardIO(protocol);

reactor.run()
