#!/usr/bin/perl -w

use strict;

my $username = <STDIN>;
chomp $username;

print <<EOF;

Welcome to Linux version 2.6.12-gentoo-r10 at serwer.honeyspy !
 12:53:22 up  1:48, 10 users,  load average: 0.20, 0.10, 0.08

EOF

print <<EOF;
Login: $username                              Name: (null)
Directory: /home/$username                    Shell: /bin/bash
On since Sun Nov  6 11:05 (CET) on tty1    1 hour 47 minutes idle
     (messages off)
On since Sun Nov  6 12:30 (CET) on pts/0   4 minutes 50 seconds idle
No mail.
EOF


